# -*- coding: utf-8 -*-
from . import freight_hs_code
from . import freight_pod
from . import freight_pol
from . import freight_reference_number
from . import freight_commodity
#from . import brokerage_details
from . import freight_package
from . import freight_job_request
from . import res_partner
from . import crm_lead
from . import freight_pricing
from . import order_line_section
from . import freight_pricing_charge
from . import booking_tracker
from . import sale_order
# from . import freight_pofd_destination
# from . import freight_por_origin
from . import job_management_link
from . import freight_service_details
from . import loose_cargo
from . import freight_containers
from . import vehicle_details
from . import freight_booking
from . import sale_order_template
from . import container_type
from . import partner_related_parties
from . import service_level
from . import freight_pricing_data
from . import freight_airline
from . import account_asset
from . import account_budget
from . import account_move
from . import freight_vessel
from . import freight_operation
from . import consol_details
from . import customer_valuation_charge
from . import freight_pre_advice
from . import freight_order
from . import product_quantity_summary
from . import freight_routing
from . import export_process_line
from . import freight_container_location
from . import import_process_line
from . import outturn
from . import tracking_dates
from . import freight_container_service
from . import freight_doc_line
from . import freight_allocated_packlines
